language: csharp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    # Packages required for android build
    - libc6-i386
    - lib32stdc++6
    - lib32gcc1
    - lib32ncurses5
    - lib32z1
    # packages for python
    - python3.5
before_install:
  # Attempt to work around fact that node modules mess up rvm
  - PATH=`echo $PATH | sed "s/\.\/node_modules\/\.bin//g"`;
  - export PATH=$PATH:./node_modules/.bin;
install:
  # Install npm
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4
  - npm install -g npm@'>=1.4.3'
  - npm install
  # Install ruby dependencies
  - rvm use 2.3.0 --install --binary --fuzzy
  - gem install bundler
  - bundle install
  - pip install --user tox
  # Install android SDK
  - mkdir android
  - wget -qO- "http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz" | tar -zxv -C ./android
  - echo y | ./android/android-sdk-linux/tools/android update sdk --all --filter platform-tools,android-23,build-tools-23.0.1 --no-ui --force
  - echo y | ./android/android-sdk-linux/tools/android update sdk --all --filter extra-android-support,extra-android-m2repository,extra-google-m2repository --no-ui --force
  - export ANDROID_HOME=`pwd`/android/android-sdk-linux
  # Install NetCore RC2
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2-003121 -y
script:
  - gulp
after_script:
  - echo "========== Server log: ============"
  - pwd
  - ls -al
  - ls -al TestResults
  - cat TestResults/*.log
notifications:
  slack:
    secure: d0PFVLcyqcMxNtmZ8JaEpIBzXbUbZCgKs8QtBB5qEIXDnxflSR3AhczlILNhTBKtMEBlwVzsz65yP09XcmvB6xpAfJbHqSRzk2frKa5viPcAD8Wr/NYamt9/UiTCsnql8MqzjVy0tLdMscXKRmsUey4YF570zl0b7gAbq7XTqxM=
